#!/bin/sh
file=${1:-./webcam.avi}
args=$2
gst-launch-1.0 --gst-plugin-path=. filesrc location="$file" ! decodebin \
	! videoconvert ! video/x-raw,format=RGBx\
	! webcamfilter $args \
	! videoconvert ! video/x-raw,format=YUY2 \
	! avimux ! filesink location=./out.avi
